---
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: pet_rescue_development

    ports:
      - 5432

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "bwoa", "-d", "pet_rescue_development"]
      interval: 10s
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
